BookStoreMVC/BookStore.WebUI/Controllers/CartController.cs
using BookStore.Domain.Abstract;
using BookStore.Domain.Entities;
using BookStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IBookRepository repository;
        private IOrderProcessor orderProcessor;
        public CartController(IBookRepository bookRep, IOrderProcessor orderProcessorParam)
        {
            repository = bookRep;
            orderProcessor = orderProcessorParam;
        }

        public ViewResult Index(Cart cart, string returnU)
        {
            return View(new CartIndexViewModel { Cart = cart, ReturnU = returnU });
        }

        public RedirectToRouteResult AddToCart( Cart cart, int isbn, string returnU)
        {
            Book book = repository.Books.FirstOrDefault(b=>b.ISBN==isbn);
            if (book != null)
            {
                cart.AddItem(book);
            }
            return RedirectToAction("Index", new { returnU }); // index
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int isbn, string returnU)
        {
            Book book = repository.Books.FirstOrDefault(b => b.ISBN == isbn);
            if (book != null)
            {
                cart.RemoveItem(book);
            }
            return RedirectToAction("Index", new { returnU } ); // index
        }        

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult CheckOut()
        {
            return View(new ShippingDetails());
        }



        [HttpPost]
        public ViewResult CheckOut(Cart cart, ShippingDetails shippingD)
        {
            if(cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty !!");
            }

            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingD);
                cart.ClearAll();
                return View("Completed");
            }
            else
            {
                return View(shippingD);
            }
           
        }

    }
}

BookStoreMVC/BookStore.WebUI/Controllers/NavController.cs
using BookStore.Domain.Abstract;
using BookStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IBookRepository repository;

        public NavController(IBookRepository bookRep)
        {
            repository = bookRep;
        }
        public PartialViewResult Menu(string specilization = null)
        {
            ViewBag.SelectedSpec = specilization;
            IEnumerable<string> Books = repository.Books
                       .Select(b => b.Specialization)
                       .Distinct();
            //string viewName = mobileLayout ? "MenuHorizontal":"Menu";
            //return PartialView(viewName, Books);
            return PartialView(Books);
        }
    }
}

BookStoreMVC/BookStore.WebUI/Views/Shared/BookSummary.Mobile.cshtml
@model BookStore.Domain.Entities.Book
<div data-role="collapsible" data-collapsed="false" data-content-theme="c">
    <h2>
        <strong>@Model.title</strong>
    </h2>
    <div class="ui-grid-b">
        <div class="ui-block-a">
            @Model.Description
        </div>
        <div class="ui-block-b">
            <strong>@Model.Price.ToString("c")</strong>
        </div>
        <div class="ui-block-c">
            @using (Html.BeginForm("AddToCart", "Cart"))
            {
                @Html.HiddenFor(b => b.ISBN)
                @Html.Hidden("returnU", Request.Url.PathAndQuery)
                <input type="submit" data-inline="true" data-mini="true" value="Add to cart" />
            }
        </div>
    </div>
</div>

BookStoreMVC/BookStore.WebUI/Views/Shared/BookSummary.cshtml
@model BookStore.Domain.Entities.Book
<div class="well">
    <h3>
        <strong>@Model.title</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("c")</span>
    </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="">
            @Html.HiddenFor(b=>b.ISBN)
            @Html.Hidden("returnU", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add to cart"/>
        </div>
    }
</div>

BookStoreMVC/BookStore.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyle.css" rel="stylesheet" />
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">
                @TempData["message"].ToString()
            </div>
        }
        @RenderBody()
    </div>

</body>
</html>

BookStoreMVC/BookStore.WebUI/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width" />
    @*<link href="~/Content/jquery.mobile-1.4.5.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-2.2.4.js"></script>
    <script src="~/Scripts/jquery.mobile-1.4.5.min.js"></script>*@

    <link href="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css" rel="stylesheet" />
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"></script>

</head>
<body>
    <div>
        <div data-role="page" id="p1">
            <div data-theme="a" data-role="header" data-position="fixed">
                <h3>BookStore</h3>
                @Html.Action("Menu", "Nav")
            </div>
            <div data-role="content">
                <ul data-role="listview" data-divider-theme="a" data-inset="true">
                    @RenderBody()
                </ul>
            </div>
        </div>
    </div>



</body>
</html>

BookStoreMVC/BookStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>

    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyle.css" rel="stylesheet" />
    <style>
        /*.test{
            padding:0px 20px 5px 10px
        }*/
        .navbar-right{
            float:right !important;
            margin-right: 15px;
            margin-left: 15px;
        }
        .navbar-brand{
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">
            <span class="hidden-xs">Book Store</span>
            <div class="visible-xs">Book</div>
            <div class="visible-xs">Store</div>
        </a>
        @Html.Action("Summary", "Cart")
    </div>
    <div class="visible-xs">
        @Html.Action("Menu", "Nav", new { mobileLayout = true})
    </div>
    <div class="row panel">
        <div id="specialization" class="col-xs-3 hidden-xs">
            @Html.Action("Menu", "Nav")
        </div> 
        <div class="col-xs-12 col-sm-8 ">
            @RenderBody()
        </div>    
    </div>

           
</body>
</html>