BookStoreMVC/BookStore.WebUI/Controllers/AdminController.cs
using BookStore.Domain.Abstract;
using BookStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.WebUI.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {

        private IBookRepository repository;
        public AdminController(IBookRepository repo)
        {
            repository = repo;
        }

        // GET: Admin
        public ViewResult Index()
        {
            return View(repository.Books);
        }

        //Edit
        public ViewResult Edit(int isbn)
        {
            Book book = repository.Books.FirstOrDefault(b => b.ISBN == isbn);
            return View(book);
        }


        [HttpPost]
        public ActionResult Edit(Book book)
        {
            if(ModelState.IsValid)
            {
                repository.SaveBook(book);
                TempData["Message"] = book.title + " has been saved";
                return RedirectToAction("Index");
            }
            else
            {
                return View(book);
            }
        }

        public ViewResult Create()
        {
               return View("Edit", new Book());
        }


        [HttpGet]
        public ActionResult Delete(int isbn)
        {
            Book deletedBook = repository.DeleteBook(isbn);
            if (deletedBook != null)
            {
                TempData["Message"] = deletedBook.title + " has been deleted";
            }
            return RedirectToAction("Index");
        }

    }
}

BookStoreMVC/BookStore.WebUI/Controllers/BookController.cs
using BookStore.Domain.Abstract;
using BookStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.WebUI.Controllers
{
    public class BookController : Controller
    {
        // GET: Book
        private IBookRepository repository;
        public int pageSize = 4;
        public BookController(IBookRepository bookRep)
        {
            repository = bookRep;
        }

        public ViewResult List(string specilization, int pageN=1)
        {
            BookListViewModel model = new BookListViewModel() {
                Books = repository.Books
                       .Where(b => specilization ==null || b.Specialization == specilization)
                       .OrderBy(b => b.ISBN)
                       .Skip((pageN - 1) * pageSize)
                       .Take(pageSize),
                PagingInfo = new PagingInfo() { CurrentPage = pageN, ItemsPerPage = pageSize, TotalItem =specilization == null ? repository.Books.Count(): repository.Books.Where(b => b.Specialization == specilization).Count() },
                CurrentSpecilization = specilization
            };

            return View(model);
        }
        public ViewResult ListAll()
        {
            return View(repository.Books);
        }

    }
}

BookStoreMVC/BookStore.WebUI/Views/Admin/Edit.cshtml
@model BookStore.Domain.Entities.Book

@{
    ViewBag.Title = Model.title;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    HtmlHelper.ClientValidationEnabled = false;
    HtmlHelper.UnobtrusiveJavaScriptEnabled = false;
}


<div class="panel panel-default">
    <div class="panel-heading">
        <h2>Edit @Model.title</h2>
    </div>



    @using (Html.BeginForm("Edit", "Admin"))
    {
        //@Html.EditorForModel();
        <div class="panel-body">

            @Html.HiddenFor(b => b.ISBN)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                if (property.PropertyName != "ISBN")
                {
                    <div class="form-group">
                        <label>@(property.DisplayName ?? property.PropertyName)</label>
                        @if (property.PropertyName == "Description")
                        {
                            @Html.TextArea(property.PropertyName, null, new { @class = "form-control", rows = 5 })
                        }
                        else
                        {
                            @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
                        }
                        @Html.ValidationMessage(property.PropertyName)
                    </div>
                }
            }
           
        </div>
        <div class="panel-footer">
            <input type="submit" value="save" class="btn btn-primary" />
            @Html.ActionLink("Cancel and Return To list", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

BookStoreMVC/BookStore.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<BookStore.Domain.Entities.Book>

@{
    ViewBag.Title = "Admin: All Books";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Admin Index</h2>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>All Books</h3>
    </div>
    <div class="panel-body">
        <table class="table table-condensed table-striped table-bordered">
            <tr>
                <th class="text-right">
                    ID
                </th>
                <th>
                    Title
                </th>
                <th  class="text-right">
                    Price
                </th>
                <th>
                    Category
                </th>
                <th>
                    Actions
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-right">
                        @Html.ActionLink(item.ISBN.ToString(), "Edit", new { isbn = item.ISBN })
                    </td>
                    <td>
                        @Html.ActionLink(item.title, "Edit", new { isbn = item.ISBN })
                    </td>
                    <td class="text-right">
                        @item.Price.ToString("c")
                    </td>
                    <td>
                        @item.Specialization
                    </td>
                    <td class="text-center">
                        @Html.ActionLink("Delete", "Delete", new { isbn = item.ISBN }, new { @class = "btn btn-danger btn-xs"})
                    </td>
                </tr>
            }

        </table>
    </div>
   <div class="panel-footer">
        @Html.ActionLink("Add new Book", "Create", null, new {@class = "btn btn-default" })
        @Html.ActionLink("Back To Home", "List", "Book", null, new { @class = "btn btn-default" })
    </div>

</div>

BookStoreMVC/BookStore.WebUI/Views/Admin/IndexOld.cshtml
@model IEnumerable<BookStore.Domain.Entities.Book>

@{
    ViewBag.Title = "Admin : Index";
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <title>Index</title>
</head>
<body>
    <div> 
        <h2>Administration Page</h2>
        <p>@Html.ActionLink("Create New", "Create")</p>
        <table class="table">
            <tr>
                <th>@Html.DisplayNameFor(model=>model.title)</th>
                <th>@Html.DisplayNameFor(model => model.Description)</th>
                <th>@Html.DisplayNameFor(model => model.Price)</th>
                <th>@Html.DisplayNameFor(model => model.Specialization)</th>
            </tr>
            @foreach (var book in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(model => book.title)</td>
                    <td>@Html.DisplayFor(model => book.Description)</td>
                    <td>@Html.DisplayFor(model => book.Price)</td>
                    <td>@Html.DisplayFor(model => book.Specialization)</td>
                    <td>
                        @Html.ActionLink("Edit","Edit", new {isbn= book.ISBN }) | 
                        @Html.ActionLink("Details", "Details", new { isbn = book.ISBN }) | 
                        @Html.ActionLink("Delete", "Delete", new { isbn = book.ISBN }) |
                    </td>
                </tr>
            }
        </table>
    </div>
</body>
</html>